/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Role = IDL.Variant({
  'admin' : IDL.Null,
  'campus_police' : IDL.Null,
  'security_guard' : IDL.Null,
  'student' : IDL.Null,
});
export const EmergencyContact = IDL.Record({
  'name' : IDL.Text,
  'phone' : IDL.Text,
});
export const MedicalInfo = IDL.Record({
  'bloodType' : IDL.Text,
  'medicalConditions' : IDL.Text,
});
export const Profile = IDL.Record({
  'studentId' : IDL.Text,
  'name' : IDL.Text,
  'role' : Role,
  'emergencyContact' : EmergencyContact,
  'phone' : IDL.Text,
  'medicalInfo' : MedicalInfo,
});
export const Status = IDL.Variant({
  'new' : IDL.Null,
  'resolved' : IDL.Null,
  'acknowledged' : IDL.Null,
});
export const Time = IDL.Int;
export const Severity = IDL.Variant({
  'low' : IDL.Null,
  'high' : IDL.Null,
  'critical' : IDL.Null,
  'medium' : IDL.Null,
});
export const RecipientRole = IDL.Variant({
  'all' : IDL.Null,
  'admin' : IDL.Null,
  'campus_police' : IDL.Null,
  'security_guard' : IDL.Null,
});
export const AlertInfo = IDL.Record({
  'status' : Status,
  'incidentId' : IDL.Nat,
  'acknowledgedBy' : IDL.Opt(IDL.Principal),
  'timestamp' : Time,
  'severity' : Severity,
  'recipientRole' : RecipientRole,
});
export const Type = IDL.Variant({
  'unusual_stop' : IDL.Null,
  'safe_zone_missed' : IDL.Null,
  'suspicious_activity' : IDL.Null,
  'safe_walk_missed' : IDL.Null,
  'route_deviation' : IDL.Null,
  'voice_alert' : IDL.Null,
  'suspicious_sound' : IDL.Null,
});
export const Report = IDL.Record({
  'status' : Status,
  'description' : IDL.Text,
  'timestamp' : Time,
  'locationZone' : IDL.Text,
  'reporter' : IDL.Principal,
  'incidentType' : Type,
});
export const Status__1 = IDL.Variant({
  'pending' : IDL.Null,
  'arrived' : IDL.Null,
  'missed' : IDL.Null,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'acknowledgeAlert' : IDL.Func([IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createOrUpdateProfile' : IDL.Func([Profile], [], []),
  'endWalkSession' : IDL.Func([IDL.Nat], [], []),
  'getAllAlerts' : IDL.Func([], [IDL.Vec(AlertInfo)], ['query']),
  'getAllIncidents' : IDL.Func([], [IDL.Vec(Report)], ['query']),
  'getAllSecurityAlerts' : IDL.Func([], [IDL.Vec(AlertInfo)], ['query']),
  'getAllUsers' : IDL.Func([], [IDL.Vec(Profile)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(Profile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getIncidentDetails' : IDL.Func([IDL.Nat], [IDL.Opt(Report)], ['query']),
  'getMedicalInfo' : IDL.Func([], [IDL.Opt(MedicalInfo)], ['query']),
  'getOwnIncidents' : IDL.Func([], [IDL.Vec(Report)], ['query']),
  'getOwnProfile' : IDL.Func([], [IDL.Opt(Profile)], ['query']),
  'getRiskHeatmapData' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
      ['query'],
    ),
  'getStudentMedicalInfo' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(MedicalInfo)],
      ['query'],
    ),
  'getStudentMedicalInfoForIncident' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(MedicalInfo)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func([IDL.Principal], [IDL.Opt(Profile)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'reportIncident' : IDL.Func([Type, IDL.Text, IDL.Text], [IDL.Nat], []),
  'resolveAlert' : IDL.Func([IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([Profile], [], []),
  'setSafeZoneCheckIn' : IDL.Func([IDL.Text, Time, Status__1], [], []),
  'startWalkSession' : IDL.Func([IDL.Text, Time], [IDL.Nat], []),
  'updateAlertStatus' : IDL.Func([IDL.Nat, Status], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Role = IDL.Variant({
    'admin' : IDL.Null,
    'campus_police' : IDL.Null,
    'security_guard' : IDL.Null,
    'student' : IDL.Null,
  });
  const EmergencyContact = IDL.Record({
    'name' : IDL.Text,
    'phone' : IDL.Text,
  });
  const MedicalInfo = IDL.Record({
    'bloodType' : IDL.Text,
    'medicalConditions' : IDL.Text,
  });
  const Profile = IDL.Record({
    'studentId' : IDL.Text,
    'name' : IDL.Text,
    'role' : Role,
    'emergencyContact' : EmergencyContact,
    'phone' : IDL.Text,
    'medicalInfo' : MedicalInfo,
  });
  const Status = IDL.Variant({
    'new' : IDL.Null,
    'resolved' : IDL.Null,
    'acknowledged' : IDL.Null,
  });
  const Time = IDL.Int;
  const Severity = IDL.Variant({
    'low' : IDL.Null,
    'high' : IDL.Null,
    'critical' : IDL.Null,
    'medium' : IDL.Null,
  });
  const RecipientRole = IDL.Variant({
    'all' : IDL.Null,
    'admin' : IDL.Null,
    'campus_police' : IDL.Null,
    'security_guard' : IDL.Null,
  });
  const AlertInfo = IDL.Record({
    'status' : Status,
    'incidentId' : IDL.Nat,
    'acknowledgedBy' : IDL.Opt(IDL.Principal),
    'timestamp' : Time,
    'severity' : Severity,
    'recipientRole' : RecipientRole,
  });
  const Type = IDL.Variant({
    'unusual_stop' : IDL.Null,
    'safe_zone_missed' : IDL.Null,
    'suspicious_activity' : IDL.Null,
    'safe_walk_missed' : IDL.Null,
    'route_deviation' : IDL.Null,
    'voice_alert' : IDL.Null,
    'suspicious_sound' : IDL.Null,
  });
  const Report = IDL.Record({
    'status' : Status,
    'description' : IDL.Text,
    'timestamp' : Time,
    'locationZone' : IDL.Text,
    'reporter' : IDL.Principal,
    'incidentType' : Type,
  });
  const Status__1 = IDL.Variant({
    'pending' : IDL.Null,
    'arrived' : IDL.Null,
    'missed' : IDL.Null,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'acknowledgeAlert' : IDL.Func([IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createOrUpdateProfile' : IDL.Func([Profile], [], []),
    'endWalkSession' : IDL.Func([IDL.Nat], [], []),
    'getAllAlerts' : IDL.Func([], [IDL.Vec(AlertInfo)], ['query']),
    'getAllIncidents' : IDL.Func([], [IDL.Vec(Report)], ['query']),
    'getAllSecurityAlerts' : IDL.Func([], [IDL.Vec(AlertInfo)], ['query']),
    'getAllUsers' : IDL.Func([], [IDL.Vec(Profile)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(Profile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getIncidentDetails' : IDL.Func([IDL.Nat], [IDL.Opt(Report)], ['query']),
    'getMedicalInfo' : IDL.Func([], [IDL.Opt(MedicalInfo)], ['query']),
    'getOwnIncidents' : IDL.Func([], [IDL.Vec(Report)], ['query']),
    'getOwnProfile' : IDL.Func([], [IDL.Opt(Profile)], ['query']),
    'getRiskHeatmapData' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
        ['query'],
      ),
    'getStudentMedicalInfo' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(MedicalInfo)],
        ['query'],
      ),
    'getStudentMedicalInfoForIncident' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(MedicalInfo)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func([IDL.Principal], [IDL.Opt(Profile)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'reportIncident' : IDL.Func([Type, IDL.Text, IDL.Text], [IDL.Nat], []),
    'resolveAlert' : IDL.Func([IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([Profile], [], []),
    'setSafeZoneCheckIn' : IDL.Func([IDL.Text, Time, Status__1], [], []),
    'startWalkSession' : IDL.Func([IDL.Text, Time], [IDL.Nat], []),
    'updateAlertStatus' : IDL.Func([IDL.Nat, Status], [], []),
  });
};

export const init = ({ IDL }) => { return []; };