/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AlertInfo {
  'status' : Status,
  'incidentId' : bigint,
  'acknowledgedBy' : [] | [Principal],
  'timestamp' : Time,
  'severity' : Severity,
  'recipientRole' : RecipientRole,
}
export interface EmergencyContact { 'name' : string, 'phone' : string }
export interface MedicalInfo {
  'bloodType' : string,
  'medicalConditions' : string,
}
export interface Profile {
  'studentId' : string,
  'name' : string,
  'role' : Role,
  'emergencyContact' : EmergencyContact,
  'phone' : string,
  'medicalInfo' : MedicalInfo,
}
export type RecipientRole = { 'all' : null } |
  { 'admin' : null } |
  { 'campus_police' : null } |
  { 'security_guard' : null };
export interface Report {
  'status' : Status,
  'description' : string,
  'timestamp' : Time,
  'locationZone' : string,
  'reporter' : Principal,
  'incidentType' : Type,
}
export type Role = { 'admin' : null } |
  { 'campus_police' : null } |
  { 'security_guard' : null } |
  { 'student' : null };
export type Severity = { 'low' : null } |
  { 'high' : null } |
  { 'critical' : null } |
  { 'medium' : null };
export type Status = { 'new' : null } |
  { 'resolved' : null } |
  { 'acknowledged' : null };
export type Status__1 = { 'pending' : null } |
  { 'arrived' : null } |
  { 'missed' : null };
export type Time = bigint;
export type Type = { 'unusual_stop' : null } |
  { 'safe_zone_missed' : null } |
  { 'suspicious_activity' : null } |
  { 'safe_walk_missed' : null } |
  { 'route_deviation' : null } |
  { 'voice_alert' : null } |
  { 'suspicious_sound' : null };
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'acknowledgeAlert' : ActorMethod<[bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createOrUpdateProfile' : ActorMethod<[Profile], undefined>,
  'endWalkSession' : ActorMethod<[bigint], undefined>,
  'getAllAlerts' : ActorMethod<[], Array<AlertInfo>>,
  'getAllIncidents' : ActorMethod<[], Array<Report>>,
  'getAllSecurityAlerts' : ActorMethod<[], Array<AlertInfo>>,
  'getAllUsers' : ActorMethod<[], Array<Profile>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [Profile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getIncidentDetails' : ActorMethod<[bigint], [] | [Report]>,
  'getMedicalInfo' : ActorMethod<[], [] | [MedicalInfo]>,
  'getOwnIncidents' : ActorMethod<[], Array<Report>>,
  'getOwnProfile' : ActorMethod<[], [] | [Profile]>,
  'getRiskHeatmapData' : ActorMethod<[], Array<[string, bigint]>>,
  'getStudentMedicalInfo' : ActorMethod<[Principal], [] | [MedicalInfo]>,
  'getStudentMedicalInfoForIncident' : ActorMethod<
    [Principal],
    [] | [MedicalInfo]
  >,
  'getUserProfile' : ActorMethod<[Principal], [] | [Profile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'reportIncident' : ActorMethod<[Type, string, string], bigint>,
  'resolveAlert' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[Profile], undefined>,
  'setSafeZoneCheckIn' : ActorMethod<[string, Time, Status__1], undefined>,
  'startWalkSession' : ActorMethod<[string, Time], bigint>,
  'updateAlertStatus' : ActorMethod<[bigint, Status], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];