/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Profile {
    studentId: string;
    name: string;
    role: Role;
    emergencyContact: EmergencyContact;
    phone: string;
    medicalInfo: MedicalInfo;
}
export type Time = bigint;
export interface MedicalInfo {
    bloodType: string;
    medicalConditions: string;
}
export interface EmergencyContact {
    name: string;
    phone: string;
}
export interface AlertInfo {
    status: Status;
    incidentId: bigint;
    acknowledgedBy?: Principal;
    timestamp: Time;
    severity: Severity;
    recipientRole: RecipientRole;
}
export interface Report {
    status: Status;
    description: string;
    timestamp: Time;
    locationZone: string;
    reporter: Principal;
    incidentType: Type;
}
export enum RecipientRole {
    all = "all",
    admin = "admin",
    campus_police = "campus_police",
    security_guard = "security_guard"
}
export enum Role {
    admin = "admin",
    campus_police = "campus_police",
    security_guard = "security_guard",
    student = "student"
}
export enum Severity {
    low = "low",
    high = "high",
    critical = "critical",
    medium = "medium"
}
export enum Status {
    new_ = "new",
    resolved = "resolved",
    acknowledged = "acknowledged"
}
export enum Status__1 {
    pending = "pending",
    arrived = "arrived",
    missed = "missed"
}
export enum Type {
    unusual_stop = "unusual_stop",
    safe_zone_missed = "safe_zone_missed",
    suspicious_activity = "suspicious_activity",
    safe_walk_missed = "safe_walk_missed",
    route_deviation = "route_deviation",
    voice_alert = "voice_alert",
    suspicious_sound = "suspicious_sound"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    acknowledgeAlert(alertId: bigint): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createOrUpdateProfile(profile: Profile): Promise<void>;
    endWalkSession(sessionId: bigint): Promise<void>;
    getAllAlerts(): Promise<Array<AlertInfo>>;
    getAllIncidents(): Promise<Array<Report>>;
    getAllSecurityAlerts(): Promise<Array<AlertInfo>>;
    getAllUsers(): Promise<Array<Profile>>;
    getCallerUserProfile(): Promise<Profile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getIncidentDetails(incidentId: bigint): Promise<Report | null>;
    getMedicalInfo(): Promise<MedicalInfo | null>;
    getOwnIncidents(): Promise<Array<Report>>;
    getOwnProfile(): Promise<Profile | null>;
    getRiskHeatmapData(): Promise<Array<[string, bigint]>>;
    getStudentMedicalInfo(student: Principal): Promise<MedicalInfo | null>;
    getStudentMedicalInfoForIncident(student: Principal): Promise<MedicalInfo | null>;
    getUserProfile(user: Principal): Promise<Profile | null>;
    isCallerAdmin(): Promise<boolean>;
    reportIncident(incidentType: Type, locationZone: string, description: string): Promise<bigint>;
    resolveAlert(alertId: bigint): Promise<void>;
    saveCallerUserProfile(profile: Profile): Promise<void>;
    setSafeZoneCheckIn(zoneName: string, expectedArrivalTime: Time, status: Status__1): Promise<void>;
    startWalkSession(zoneName: string, expectedArrivalTime: Time): Promise<bigint>;
    updateAlertStatus(alertId: bigint, status: Status): Promise<void>;
}
import type { AlertInfo as _AlertInfo, EmergencyContact as _EmergencyContact, MedicalInfo as _MedicalInfo, Profile as _Profile, RecipientRole as _RecipientRole, Report as _Report, Role as _Role, Severity as _Severity, Status as _Status, Status__1 as _Status__1, Time as _Time, Type as _Type, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async acknowledgeAlert(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.acknowledgeAlert(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.acknowledgeAlert(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createOrUpdateProfile(arg0: Profile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createOrUpdateProfile(to_candid_Profile_n3(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createOrUpdateProfile(to_candid_Profile_n3(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async endWalkSession(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.endWalkSession(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.endWalkSession(arg0);
            return result;
        }
    }
    async getAllAlerts(): Promise<Array<AlertInfo>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllAlerts();
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllAlerts();
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllIncidents(): Promise<Array<Report>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllIncidents();
                return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllIncidents();
            return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllSecurityAlerts(): Promise<Array<AlertInfo>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllSecurityAlerts();
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllSecurityAlerts();
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllUsers(): Promise<Array<Profile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllUsers();
                return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllUsers();
            return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<Profile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getIncidentDetails(arg0: bigint): Promise<Report | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getIncidentDetails(arg0);
                return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getIncidentDetails(arg0);
            return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMedicalInfo(): Promise<MedicalInfo | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMedicalInfo();
                return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMedicalInfo();
            return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOwnIncidents(): Promise<Array<Report>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOwnIncidents();
                return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOwnIncidents();
            return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOwnProfile(): Promise<Profile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getOwnProfile();
                return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOwnProfile();
            return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRiskHeatmapData(): Promise<Array<[string, bigint]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRiskHeatmapData();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRiskHeatmapData();
            return result;
        }
    }
    async getStudentMedicalInfo(arg0: Principal): Promise<MedicalInfo | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getStudentMedicalInfo(arg0);
                return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStudentMedicalInfo(arg0);
            return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStudentMedicalInfoForIncident(arg0: Principal): Promise<MedicalInfo | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getStudentMedicalInfoForIncident(arg0);
                return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStudentMedicalInfoForIncident(arg0);
            return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<Profile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async reportIncident(arg0: Type, arg1: string, arg2: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.reportIncident(to_candid_Type_n32(this._uploadFile, this._downloadFile, arg0), arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.reportIncident(to_candid_Type_n32(this._uploadFile, this._downloadFile, arg0), arg1, arg2);
            return result;
        }
    }
    async resolveAlert(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.resolveAlert(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.resolveAlert(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: Profile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_Profile_n3(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_Profile_n3(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async setSafeZoneCheckIn(arg0: string, arg1: Time, arg2: Status__1): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setSafeZoneCheckIn(arg0, arg1, to_candid_Status__1_n34(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setSafeZoneCheckIn(arg0, arg1, to_candid_Status__1_n34(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async startWalkSession(arg0: string, arg1: Time): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.startWalkSession(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.startWalkSession(arg0, arg1);
            return result;
        }
    }
    async updateAlertStatus(arg0: bigint, arg1: Status): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAlertStatus(arg0, to_candid_Status_n36(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAlertStatus(arg0, to_candid_Status_n36(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_AlertInfo_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AlertInfo): AlertInfo {
    return from_candid_record_n9(_uploadFile, _downloadFile, value);
}
function from_candid_Profile_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Profile): Profile {
    return from_candid_record_n24(_uploadFile, _downloadFile, value);
}
function from_candid_RecipientRole_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RecipientRole): RecipientRole {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function from_candid_Report_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Report): Report {
    return from_candid_record_n19(_uploadFile, _downloadFile, value);
}
function from_candid_Role_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Role): Role {
    return from_candid_variant_n26(_uploadFile, _downloadFile, value);
}
function from_candid_Severity_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Severity): Severity {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_Status_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Status): Status {
    return from_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function from_candid_Type_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Type): Type {
    return from_candid_variant_n21(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n29(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Principal]): Principal | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Profile]): Profile | null {
    return value.length === 0 ? null : from_candid_Profile_n23(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Report]): Report | null {
    return value.length === 0 ? null : from_candid_Report_n18(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_MedicalInfo]): MedicalInfo | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _Status;
    description: string;
    timestamp: _Time;
    locationZone: string;
    reporter: Principal;
    incidentType: _Type;
}): {
    status: Status;
    description: string;
    timestamp: Time;
    locationZone: string;
    reporter: Principal;
    incidentType: Type;
} {
    return {
        status: from_candid_Status_n10(_uploadFile, _downloadFile, value.status),
        description: value.description,
        timestamp: value.timestamp,
        locationZone: value.locationZone,
        reporter: value.reporter,
        incidentType: from_candid_Type_n20(_uploadFile, _downloadFile, value.incidentType)
    };
}
function from_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    studentId: string;
    name: string;
    role: _Role;
    emergencyContact: _EmergencyContact;
    phone: string;
    medicalInfo: _MedicalInfo;
}): {
    studentId: string;
    name: string;
    role: Role;
    emergencyContact: EmergencyContact;
    phone: string;
    medicalInfo: MedicalInfo;
} {
    return {
        studentId: value.studentId,
        name: value.name,
        role: from_candid_Role_n25(_uploadFile, _downloadFile, value.role),
        emergencyContact: value.emergencyContact,
        phone: value.phone,
        medicalInfo: value.medicalInfo
    };
}
function from_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _Status;
    incidentId: bigint;
    acknowledgedBy: [] | [Principal];
    timestamp: _Time;
    severity: _Severity;
    recipientRole: _RecipientRole;
}): {
    status: Status;
    incidentId: bigint;
    acknowledgedBy?: Principal;
    timestamp: Time;
    severity: Severity;
    recipientRole: RecipientRole;
} {
    return {
        status: from_candid_Status_n10(_uploadFile, _downloadFile, value.status),
        incidentId: value.incidentId,
        acknowledgedBy: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.acknowledgedBy)),
        timestamp: value.timestamp,
        severity: from_candid_Severity_n13(_uploadFile, _downloadFile, value.severity),
        recipientRole: from_candid_RecipientRole_n15(_uploadFile, _downloadFile, value.recipientRole)
    };
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    new: null;
} | {
    resolved: null;
} | {
    acknowledged: null;
}): Status {
    return "new" in value ? Status.new : "resolved" in value ? Status.resolved : "acknowledged" in value ? Status.acknowledged : value;
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    low: null;
} | {
    high: null;
} | {
    critical: null;
} | {
    medium: null;
}): Severity {
    return "low" in value ? Severity.low : "high" in value ? Severity.high : "critical" in value ? Severity.critical : "medium" in value ? Severity.medium : value;
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    all: null;
} | {
    admin: null;
} | {
    campus_police: null;
} | {
    security_guard: null;
}): RecipientRole {
    return "all" in value ? RecipientRole.all : "admin" in value ? RecipientRole.admin : "campus_police" in value ? RecipientRole.campus_police : "security_guard" in value ? RecipientRole.security_guard : value;
}
function from_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    unusual_stop: null;
} | {
    safe_zone_missed: null;
} | {
    suspicious_activity: null;
} | {
    safe_walk_missed: null;
} | {
    route_deviation: null;
} | {
    voice_alert: null;
} | {
    suspicious_sound: null;
}): Type {
    return "unusual_stop" in value ? Type.unusual_stop : "safe_zone_missed" in value ? Type.safe_zone_missed : "suspicious_activity" in value ? Type.suspicious_activity : "safe_walk_missed" in value ? Type.safe_walk_missed : "route_deviation" in value ? Type.route_deviation : "voice_alert" in value ? Type.voice_alert : "suspicious_sound" in value ? Type.suspicious_sound : value;
}
function from_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    campus_police: null;
} | {
    security_guard: null;
} | {
    student: null;
}): Role {
    return "admin" in value ? Role.admin : "campus_police" in value ? Role.campus_police : "security_guard" in value ? Role.security_guard : "student" in value ? Role.student : value;
}
function from_candid_variant_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Report>): Array<Report> {
    return value.map((x)=>from_candid_Report_n18(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Profile>): Array<Profile> {
    return value.map((x)=>from_candid_Profile_n23(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_AlertInfo>): Array<AlertInfo> {
    return value.map((x)=>from_candid_AlertInfo_n8(_uploadFile, _downloadFile, x));
}
function to_candid_Profile_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Profile): _Profile {
    return to_candid_record_n4(_uploadFile, _downloadFile, value);
}
function to_candid_Role_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Role): _Role {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_Status__1_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Status__1): _Status__1 {
    return to_candid_variant_n35(_uploadFile, _downloadFile, value);
}
function to_candid_Status_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Status): _Status {
    return to_candid_variant_n37(_uploadFile, _downloadFile, value);
}
function to_candid_Type_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Type): _Type {
    return to_candid_variant_n33(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    studentId: string;
    name: string;
    role: Role;
    emergencyContact: EmergencyContact;
    phone: string;
    medicalInfo: MedicalInfo;
}): {
    studentId: string;
    name: string;
    role: _Role;
    emergencyContact: _EmergencyContact;
    phone: string;
    medicalInfo: _MedicalInfo;
} {
    return {
        studentId: value.studentId,
        name: value.name,
        role: to_candid_Role_n5(_uploadFile, _downloadFile, value.role),
        emergencyContact: value.emergencyContact,
        phone: value.phone,
        medicalInfo: value.medicalInfo
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Type): {
    unusual_stop: null;
} | {
    safe_zone_missed: null;
} | {
    suspicious_activity: null;
} | {
    safe_walk_missed: null;
} | {
    route_deviation: null;
} | {
    voice_alert: null;
} | {
    suspicious_sound: null;
} {
    return value == Type.unusual_stop ? {
        unusual_stop: null
    } : value == Type.safe_zone_missed ? {
        safe_zone_missed: null
    } : value == Type.suspicious_activity ? {
        suspicious_activity: null
    } : value == Type.safe_walk_missed ? {
        safe_walk_missed: null
    } : value == Type.route_deviation ? {
        route_deviation: null
    } : value == Type.voice_alert ? {
        voice_alert: null
    } : value == Type.suspicious_sound ? {
        suspicious_sound: null
    } : value;
}
function to_candid_variant_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Status__1): {
    pending: null;
} | {
    arrived: null;
} | {
    missed: null;
} {
    return value == Status__1.pending ? {
        pending: null
    } : value == Status__1.arrived ? {
        arrived: null
    } : value == Status__1.missed ? {
        missed: null
    } : value;
}
function to_candid_variant_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Status): {
    new: null;
} | {
    resolved: null;
} | {
    acknowledged: null;
} {
    return value == Status.new ? {
        new_: null
    } : value == Status.resolved ? {
        resolved: null
    } : value == Status.acknowledged ? {
        acknowledged: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Role): {
    admin: null;
} | {
    campus_police: null;
} | {
    security_guard: null;
} | {
    student: null;
} {
    return value == Role.admin ? {
        admin: null
    } : value == Role.campus_police ? {
        campus_police: null
    } : value == Role.security_guard ? {
        security_guard: null
    } : value == Role.student ? {
        student: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
